import { ChangeDetectorRef, Component, LOCALE_ID, OnInit, ViewChild } from '@angular/core';
import { ApiService } from 'src/app/shared/services/api.service';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarVerticalPosition } from '@angular/material/snack-bar';
import { RegisterTable } from 'src/app/shared/interfaces/register-table-interface';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss'],
  providers: [{ provide: LOCALE_ID, useValue: 'es-ES' }] 
})

export class RegisterComponent implements OnInit {
  
  displayedColumns: string[] = [
    'number', 
    'name', 
    'first_period', 
    'second_period', 
    'third_period', 
    'fourth_period', 
    'outside_period', 
    'legal_founding', 
    'snitching_supervisor', 
    'evidence', 
    '1minute',
    '5minute',
    'exam_questions',
    'correct_answers',
    'incorrect_answers',
    'incomplete_sanctions'
  ];

  dataSource: RegisterTable[] = [
    {
      num: '1',
      name: "Declaración provisional mensual del Impuesto Sobre la Renta",
      first_period: "13 del mes siguiente",
      second_period: "14 del mes siguiente",
      third_period: "15 del mes siguiente",
      fourth_period: "16 del mes siguiente",
      outside_period: "17 del mes siguiente",
      legal_founding: "Art. 14 LISR",
      snitching_supervisor: "16 del mes siguiente",
      evidence: "Acuse, declaración y evidencia",
      one_minute: "SI",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '2',
      name: "Declaración definitiva mensual del Impuesto al Valor Agregado",
      first_period: "13 del mes siguiente",
      second_period: "14 del mes siguiente",
      third_period: "15 del mes siguiente",
      fourth_period: "16 del mes siguiente",
      outside_period: "17 del mes siguiente",
      legal_founding: "Art. 5-D LIVA",
      snitching_supervisor: "16 del mes siguiente",
      evidence: "Acuse, declaración y evidencia de pago",
      one_minute: "SI",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '3',
      name: "Presentación de DIOT (Declaración Informativa de Operaciones con Terceros)",
      first_period: "26 del mes siguiente",
      second_period: "27 del mes siguiente",
      third_period: "28 del mes siguiente",
      fourth_period: "29 del mes siguiente",
      outside_period: "30 al 31 del mes siguiente",
      legal_founding: "Art. 32 fracción VIII LIVA",
      snitching_supervisor: "29 del mes siguiente",
      evidence: "Acuse de envío",
      one_minute: "SI",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '4',
      name: "Autorización IMSS ante el IMSS (REPSE)",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '5',
      name: "Vigencia de sellos para facturar (Certificado de Sellos Digitales)",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '6',
      name: "Opinión de cumplimiento del SAT",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '7',
      name: "Revisión de buzón tributario",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8',
      name: "Pre-cierre contable semanal, validando el IVA a esta fecha",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.1',
      name: "Primer lunes del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "12:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.2',
      name: "Segundo lunes del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "12:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.3',
      name: "Tercer lunes del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "12:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.4',
      name: "Cuarto lunes del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "12:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.5',
      name: "Antepenúltimo día del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "2:00 p.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.6',
      name: "Penúltimo día del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "12:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "12:00 a.m.",
      legal_founding: "N/A",
      snitching_supervisor: "12:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.7',
      name: "Último día del mes para contabilizar hasta el día anterior",
      first_period: "9:00 a.m.",
      second_period: "10:30 a.m.",
      third_period: "11:00 a.m.",
      fourth_period: "",
      outside_period: "",
      legal_founding: "N/A",
      snitching_supervisor: "11:00 a.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '8.7.1',
      name: "Último día del mes para contabilizar los movimientos del día ocurridos hasta las 12pm",
      first_period: "12:00 p.m.",
      second_period: "12:30 p.m.",
      third_period: "1:00 p.m.",
      fourth_period: "1:30 p.m.",
      outside_period: "2:00 p.m.",
      legal_founding: "N/A",
      snitching_supervisor: "1:30 p.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num:' 8.7.2',
      name: "Último día del mes para contabilizar los movimientos del día ocurridos hasta las 4pm",
      first_period: "4:00 p.m.",
      second_period: "4:15 p.m.",
      third_period: "4:30 p.m.",
      fourth_period: "4:45 p.m.",
      outside_period: "5:00 p.m.",
      legal_founding: "N/A",
      snitching_supervisor: "4:30 p.m.",
      evidence: "Estado de cuenta, conciliación bancaria, auxiliares de IVA y pre-determinación de IVA a esta fecha",
      one_minute: "Maricela",
      five_minute: "Angélica",
      exam_questions: "3 preguntas para video de 1 minuto y 20 preguntas para video de 5 minutos",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '9',
      name: "Emisión de recibos de pago conforme se realice el cobro",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  },
  {
      num: '10',
      name: "Vigencia de la e.firma (antes FIEL)",
      first_period: "",
      second_period: "",
      third_period: "",
      fourth_period: "",
      outside_period: "",
      legal_founding: "Art. 29-A fracción VII inciso b) CFF",
      snitching_supervisor: "",
      evidence: "",
      one_minute: "",
      five_minute: "",
      exam_questions: "",
      correct_answers: "",
      incorrect_answers: "",
      incomplete_sanctions: ""
  }
  ];

  constructor(private apiService:ApiService, public dialog: MatDialog, public snackBar: MatSnackBar, private cdr: ChangeDetectorRef,) {}

  ngOnInit(): void {

  }
}
